### PR TITLE
Changed hamburger event handler to allow admin content to trigger it.

### PR DESCRIPTION
**Pull request by igorshtopor**

### CODE REVIEW

**Comment by igorshtopor** [comment]
@egutter Hi Emilio, please review. This also need to deployed to stage and production. Also how can I access admin panel on staging?

**Comment by egutter** [comment]
> @egutter Hi Emilio, please review. This also need to deployed to stage and production. Also how can I access admin panel on staging?

@igorshtopor I need your email address to add your user to stg admin

**Comment by igorshtopor** [comment]
@egutter `iki@jetthoughts.com`

**Comment by igorshtopor** [comment]
@egutter Can we do a production deploy?

**Pull request merged**
